name: Build and Publish

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      # https://github.com/actions/setup-java
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      # https://github.com/actions/checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Build Docker image with Maven
      - name: Build with Maven
        run: ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName=${{ env.IMAGE_NAME }}
        working-directory: ./demo

      # https://github.com/docker/metadata-action
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}

      # https://github.com/docker/login-action
      - name: Login to ${{ env.REGISTRY }} registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      # https://github.com/akhilerm/tag-push-action
      - name: Push Docker image to ${{ env.REGISTRY }} registry
        uses: akhilerm/tag-push-action@v2.1.0
        with:
          src: ${{ env.IMAGE_NAME }}
          dst: ${{ steps.meta.outputs.tags }}
